name: build and push

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

on:
  workflow_dispatch:

jobs:

  login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    needs: login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and push all
        run: |
          for d in */ ; do
            cd $d
            docker build -t ${d%?} .
            docker tag ${d%?}:latest ghcr.io/mijndert/${d%?}:latest
            docker push ghcr.io/mijndert/${d%?}:latest
          done

