name: build and push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: build and push all sub-directories
        run: |
          for d in */ ; do
            cd $d
            docker build -t ${d%?} .
            docker tag ${d%?}:latest ghcr.io/mijndert/${d%?}:latest
            docker push ghcr.io/mijndert/${d%?}:latest
          done
